backend:
  name: github
  repo: citrapricylia-am/dummy-site   # ganti dengan repo kamu
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "data/homepage.yml"
        label: "Konten Homepage"
        name: "home"
        fields:
          - { label: "Judul Hero", name: "hero_title", widget: "string" }
          - { label: "Deskripsi Hero", name: "hero_desc", widget: "text" }
